# Generated by Django 4.0.2 on 2022-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('day', models.DateField()),
                ('weight', models.FloatField()),
            ],
            options={
                'verbose_name': 'weight',
                'verbose_name_plural': 'weights',
            },
        ),
    ]
